apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: api-user
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app.kubernetes.io/name: frontend