apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      run: frontend
  template:
    metadata:
      labels:
        run: frontend
    spec:
      containers:
        - name: frontend
          image: docker.io/nikolaslacerda/udagram-frontend:v1
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
            limits:
              memory: "1024Mi"
          envFrom:
            - secretRef:
                name: env-secret
            - configMapRef:
                name: env-config
            - secretRef:
                name: aws-secret
          ports:
            - containerPort: 80